# Generated by Django 4.0.1 on 2022-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('bedno', models.IntegerField()),
                ('patientid', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('doctorname', models.CharField(max_length=200)),
                ('aadharno', models.PositiveBigIntegerField()),
                ('deviceid', models.IntegerField(unique=True)),
            ],
        ),
    ]
