# Generated by Django 4.0.1 on 2022-01-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard',
            new_name='Patients',
        ),
    ]
